version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ${PROJECT_NAME}_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    container_name: ${PROJECT_NAME}_fastapi
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "${APP_PORT}"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn run:app --host ${APP_HOST} --port ${APP_PORT} --workers 4"

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
  

  certbot:
    image: certbot/certbot
    container_name: ${PROJECT_NAME}_certbot
    env_file:
      - .env
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  pg_data:
  certbot-etc:
  certbot-www:
