"""all models migration

Revision ID: 8b60ceacf022
Revises: 
Create Date: 2025-07-16 22:24:21.731016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b60ceacf022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('contacted', 'project_started', 'continuing', 'finished', 'rejected', 'need_to_call', name='customerstatus'), nullable=False),
    sa.Column('assistant_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_donation', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usd_to_uzs', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('incomer', 'outcomer', name='financetype'), nullable=False),
    sa.Column('status', sa.Enum('one_time', 'monthly', name='financestatus'), nullable=False),
    sa.Column('card', sa.Enum('card1', 'card2', 'card3', name='cardtype'), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('summ', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('UZS', 'USD', name='currencytype'), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('donation', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('donation_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('transaction_status', sa.Enum('real', 'statistical', name='transactionstatus'), nullable=True),
    sa.Column('initial_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_site_on', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('company_code', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=50), nullable=True),
    sa.Column('default_salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('role', sa.Enum('CEO', 'financial_director', 'member', 'customer', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summ', sa.DECIMAL(precision=19, scale=2), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('update_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('potential_monthly', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_page_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.Enum('ceo', 'payment_list', 'project_toggle', 'crm', 'finance_list', name='pagename'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_page_permission')
    op.drop_table('monthly_update')
    op.drop_table('message')
    op.drop_table('credit_card')
    op.drop_table('user_payment')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('site_control')
    op.drop_table('payment')
    op.drop_table('finance')
    op.drop_table('exchange_rate')
    op.drop_table('donation_balance')
    op.drop_table('customer')
    # ### end Alembic commands ###
