"""Add cascade delete to foreign keys

Revision ID: 9379863ec8ea
Revises: 68d6480aee32
Create Date: 2025-08-06 21:02:12.116252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9379863ec8ea'
down_revision: Union[str, Sequence[str], None] = '68d6480aee32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('message_sender_id_fkey'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('message_receiver_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_receiver_id_fkey'), 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('message_sender_id_fkey'), 'message', 'user', ['sender_id'], ['id'])
    # ### end Alembic commands ###
